# Generated by Django 4.0.5 on 2022-07-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipl_data_analyzer', '0010_delete_deliveriesdatamodel_delete_matchesdatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesDataModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(default=0, max_length=40, null=True)),
                ('city', models.CharField(max_length=25)),
                ('date', models.DateField(null=True)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('toss_winner', models.CharField(max_length=50)),
                ('toss_decision', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('dl_applied', models.IntegerField(default=0, null=True)),
                ('winner', models.CharField(max_length=50)),
                ('win_by_runs', models.IntegerField(default=0, null=True)),
                ('win_by_wickets', models.IntegerField(default=0, null=True)),
                ('player_of_match', models.CharField(max_length=40)),
                ('venue', models.CharField(max_length=100)),
                ('umpire1', models.CharField(max_length=40)),
                ('umpire2', models.CharField(max_length=40)),
                ('umpire3', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveriesDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField(default=0, null=True)),
                ('batting_team', models.CharField(max_length=50)),
                ('bowling_team', models.CharField(max_length=50)),
                ('over', models.IntegerField(default=0, null=True)),
                ('ball', models.IntegerField(default=0, null=True)),
                ('batsman', models.CharField(max_length=40)),
                ('non_striker', models.CharField(max_length=40)),
                ('bowler', models.CharField(max_length=40)),
                ('is_super_over', models.IntegerField(default=0, null=True)),
                ('wide_runs', models.IntegerField(default=0, null=True)),
                ('bye_runs', models.IntegerField(default=0, null=True)),
                ('legbye_runs', models.IntegerField(default=0, null=True)),
                ('noball_runs', models.IntegerField(default=0, null=True)),
                ('penalty_runs', models.IntegerField(default=0, null=True)),
                ('batsman_runs', models.IntegerField(default=0, null=True)),
                ('extra_runs', models.IntegerField(default=0, null=True)),
                ('total_runs', models.IntegerField(default=0, null=True)),
                ('player_dismissed', models.CharField(max_length=40)),
                ('dismissal_kind', models.CharField(max_length=30)),
                ('fielder', models.CharField(max_length=40)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_data_analyzer.matchesdatamodel')),
            ],
        ),
    ]
